server:
  port: 8088
spring:
  application:
    name: ClothesDP
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ClothesDP?useSSL=false&serverTimezone=UTC
    username: root
    password: "00000000"
  redis:
    host: localhost
    port: 6379
    #    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  #    rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.liyifu.clothesdp.model.entity # 别名扫描包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.liyifu.clothesdp: debug